import React, { useContext } from "react";
import { GlobalContext } from "../context/GlobalContext";
const CookiesAndPolicy = () => {
  const { palette } = useContext(GlobalContext);
  return (
    <div className="w-full h-auto flex flex-col justify-start items-start">
      <div className="w-full h-auto  flex flex-col justify-start items-center px-2 md:px-10 py-2 md:py-6 lg:py-8 mt-10 gap-4 my-16 lg:gap-8">
        <div className="w-full h-auto flex flex-col gap-2 items-center justify-center">
          <h1
            className="text-4xl  font-bold  "
            style={{ color: palette?.brand }}
          >
            Cookie Policy
          </h1>
          <p>
            <strong>Updated at January 1st, 2024</strong>
          </p>
        </div>

        <div className="w-full lg:w-[90%] h-auto px-0 lg:px-20 relative">
          <div className="w-full h-auto z-[1000] rounded-3xl flex flex-col gap-3 justify-start items-start  text-md font-medium bg-gray-50 p-6 lg:p-10 ">
            <h2>Definitions and Key Terms</h2>
            <p>
              To help explain things as clearly as possible in this Cookie
              Policy, every time any of these terms are referenced, are strictly
              defined as:
            </p>
            <ul>
              <li>
                <strong>Cookie:</strong> small amount of data generated by a
                website and saved by your web browser. It is used to identify
                your browser, provide analytics, remember information about you
                such as your language preference or login information.
              </li>
              <li>
                <strong>Company:</strong> when this policy mentions “Company,”
                “we,” “us,” or “our,” it refers to Now You Know Nashville, that
                is responsible for your information under this Cookie Policy.
              </li>
              <li>
                <strong>Device:</strong> any internet connected device such as a
                phone, tablet, computer or any other device that can be used to
                visit Now You Know Nashville and use the services.
              </li>
              <li>
                <strong>Personal Data:</strong> any information that directly,
                indirectly, or in connection with other information — including
                a personal identification number — allows for the identification
                or identifiability of a natural person.
              </li>
              <li>
                <strong>Service:</strong> refers to the service provided by Now
                You Know Nashville as described in the relative terms (if
                available) and on this platform.
              </li>
              <li>
                <strong>Third-party service:</strong> refers to advertisers,
                contest sponsors, promotional and marketing partners, and others
                who provide our content or whose products or services we think
                may interest you.
              </li>
              <li>
                <strong>App/Application:</strong> Now You Know Nashville app,
                refers to the SOFTWARE PRODUCT identified above.
              </li>
              <li>
                <strong>You:</strong> a person or entity that is registered with
                Now You Know Nashville to use the Services.
              </li>
            </ul>

            <h2>Introduction</h2>
            <p>
              This Cookie Policy explains how Now You Know Nashville and its
              affiliates (collectively "Now You Know Nashville", "we", "us", and
              "ours"), use cookies and similar technologies to recognize you
              when you visit our app, including without limitation and any
              related URLs, mobile or localized versions and related domains /
              sub-domains ("Websites"). It explains what these technologies are
              and why we use them, as well as the choices for how to control
              them.
            </p>

            <h2>What is a Cookie?</h2>
            <p>
              A cookie is a small text file that is stored on your computer or
              other internet connected device in order to identify your browser,
              provide analytics, remember information about you such as your
              language preference or login information. They're completely safe
              and can't be used to run programs or deliver viruses to your
              device.
            </p>

            <h2>Why Do We Use Cookies?</h2>
            <p>
              We use first party and/or third-party cookies on our app for
              various purposes such as:
            </p>
            <ul>
              <li>To facilitate the operation and functionality of our app;</li>
              <li>
                To improve your experience of our app and make navigating around
                them quicker and easier;
              </li>
              <li>... (remaining content omitted for brevity)</li>
            </ul>

            <h2>How You Can Manage Cookies?</h2>
            <p>
              Most browsers allow you to control cookies through their
              'settings' preferences. However, if you limit the ability of
              websites to set cookies, you may worsen your overall user
              experience, since it will no longer be personalized to you.
            </p>
            <p>... (remaining content omitted for brevity)</p>

            <h2>Changes To Our Cookie Policy</h2>
            <p>
              We may change our Service and policies, and we may need to make
              changes to this Cookie Policy so that they accurately reflect our
              Service and policies.
            </p>
            <p>... (remaining content omitted for brevity)</p>

            <h2>Your Consent</h2>
            <p>
              By using our app, registering an account, or making a purchase,
              you hereby consent to our Cookie Policy and agree to its terms.
            </p>

            <h2>Contact Us</h2>
            <p>
              Don't hesitate to contact us if you have any questions regarding
              our Cookie Policy.
            </p>
            <p>
              Via this Link:{" "}
              <a href="www.nowyouknownashville.com">
                www.nowyouknownashville.com
              </a>
            </p>
          </div>
        </div>
      </div>
    </div>
  );
};

export default CookiesAndPolicy;
