import React from "react";
import { useContext } from "react";
import { GlobalContext } from "../context/GlobalContext";

const Privacy = () => {
  const { palette } = useContext(GlobalContext);
  return (
    <div className="w-full h-auto flex flex-col justify-start items-start">
      <div className="w-full h-auto  flex flex-col justify-start items-center px-2 md:px-10 py-2 md:py-6 lg:py-8 mt-10 gap-4 my-16 lg:gap-8">
        <div className="w-full h-auto flex items-center justify-center">
          <h1
            className="text-4xl  font-bold  "
            style={{ color: palette?.brand }}
          >
            Privacy Policy
          </h1>
        </div>

        <div className="w-full lg:w-[90%] h-auto px-0 lg:px-20 relative">
          <div className="w-full h-auto z-[1000] rounded-3xl flex flex-col gap-3 justify-start items-start  text-md font-medium bg-gray-50 p-6 lg:p-10 ">
            THIS PRIVACY POLICY (THIS "POLICY") DESCRIBES THE PRIVACY PRACTICES
            OF MAIDSIMPL WITH RESPECT TO INFORMATION COLLECTED WHEN YOU SIGN UP
            FOR, USE, ACCESS OR OTHERWISE INTERACT WITH WWW.MAIDSIMPL.COM (THE
            "SITE") AND ANY ONLINE SERVICES AND PRODUCTS OF MAIDSIMPL, INCLUDING
            MOBILE APPLICATIONS AND WEBSITES OR APPLICATIONS OPERATED BY
            MAIDSIMPL AND CONNECTED PRODUCTS AND SERVICES (COLLECTIVELY,
            INCLUDING THE SITES, THE "SERVICES") THAT REFERENCE THIS POLICY, AND
            HOW WE USE AND SHARE THAT INFORMATION. BY USING THE SERVICES
            (INCLUDING THE SITES) YOU CONSENT TO THE TERMS OF THIS POLICY.
            <br />
            <br />
            YOU CAN REACH US AT SUPPORT@MAIDSIMPL.COM IF YOU HAVE FURTHER
            QUESTIONS.
            <br />
            <br />
            BY USING THE SERVICES YOU CONSENT TO THE COLLECTION, USE AND
            TRANSFER OF YOUR PERSONAL DATA FOR PROCESSING AS DESCRIBED IN THIS
            PRIVACY POLICY.
            <br />
            <br />
            PERSONAL DATA WE COLLECT MAY BE STORED AND PROCESSED IN THE UNITED
            STATES OR ANY OTHER COUNTRY IN WHICH MAIDSIMPL OR ITS AFFILIATES,
            SUBSIDIARIES, AGENTS, OR THIRD PARTY SERVICE PROVIDERS MAINTAIN
            FACILITIES AND/OR INFRASTRUCTURE, AND BY USING THE SERVICES AND
            SUBMITTING INFORMATION TO US, YOU CONSENT TO THE TRANSFER,
            PROCESSING AND STORAGE OF SUCH INFORMATION OUTSIDE OF YOUR COUNTRY.
            UNLESS APPLICABLE LAW REQUIRES DIFFERENT SECURITY AND PROTECTIONS TO
            BE APPLIED IN ANY GIVEN RELEVANT JURISDICTION, WE APPLY THE SAME
            PRINCIPLES IN USING, HANDLING AND TRANSMITTING DATA AS DESCRIBED IN
            THIS PRIVACY POLICY IN ALL OF OUR OPERATIONS. IF YOU DO NOT AGREE
            WITH ANY PART OF THIS PRIVACY POLICY OR OUR TERMS AND CONDITIONS,
            PLEASE DO NOT ACCESS OR CONTINUE TO USE ANY OF THE SERVICES OR
            OTHERWISE PROVIDE YOUR PERSONAL DATA.
            <br />
            <br />
            YOU CAN REACH US AT SUPPORT@MAIDSIMPL.COM IF YOU HAVE FURTHER
            QUESTIONS.
            <br />
            <br />
            BY USING THE SERVICES YOU CONSENT TO THE COLLECTION, USE AND
            TRANSFER OF YOUR PERSONAL DATA FOR PROCESSING AS DESCRIBED IN THIS
            PRIVACY POLICY.
            <br />
            <br />
            PERSONAL DATA WE COLLECT MAY BE STORED AND PROCESSED IN THE UNITED
            STATES OR ANY OTHER COUNTRY IN WHICH MAIDSIMPL OR ITS AFFILIATES,
            SUBSIDIARIES, AGENTS, OR THIRD PARTY SERVICE PROVIDERS MAINTAIN
            FACILITIES AND/OR INFRASTRUCTURE, AND BY USING THE SERVICES AND
            SUBMITTING INFORMATION TO US, YOU CONSENT TO THE TRANSFER,
            PROCESSING AND STORAGE OF SUCH INFORMATION OUTSIDE OF YOUR COUNTRY.
            UNLESS APPLICABLE LAW REQUIRES DIFFERENT SECURITY AND PROTECTIONS TO
            BE APPLIED IN ANY GIVEN RELEVANT JURISDICTION, WE APPLY THE SAME
            PRINCIPLES IN USING, HANDLING AND TRANSMITTING DATA AS DESCRIBED IN
            THIS PRIVACY POLICY IN ALL OF OUR OPERATIONS. IF YOU DO NOT AGREE
            WITH ANY PART OF THIS PRIVACY POLICY OR OUR TERMS AND CONDITIONS,
            PLEASE DO NOT ACCESS OR CONTINUE TO USE ANY OF THE SERVICES OR
            OTHERWISE PROVIDE YOUR PERSONAL DATA.
            <br />
            <br />
            THIS POLICY COVERS THE FOLLOWING AREAS:
            <br />
            <br />
            INFORMATION WE COLLECT
            <br />
            HOW WE USE YOUR INFORMATION
            <br />
            III. HOW WE SHARE YOUR INFORMATION
            <br />
            <br />
            DATA SECURITY
            <br />
            DATA RETENTION
            <br />
            COOKIES AND OTHER DATA COLLECTION TOOLS
            <br />
            VII. HOW TO MANAGE YOUR PRIVACY SETTINGS
            <br />
            <br />
            VIII. CHILDREN
            <br />
            <br />
            REGION-SPECIFIC DISCLOSURES
            <br />
            THIRD PARTIES WE DON'T OWN OR CONTROL HOW TO CONTACT US
            <br />
            XII. AMENDMENTS
            <br />
            <br />
            INFORMATION WE COLLECT
            <br />
            MAIDSIMPL COLLECTS INFORMATION FROM USERS IN CONNECTION WITH THE
            SERVICES. WE COLLECT BOTH PERSONAL DATA AND NON-PERSONAL
            INFORMATION. "PERSONAL DATA" MEANS INFORMATION THAT RELATES TO YOU
            AND IDENTIFIES YOU PERSONALLY, EITHER ALONE OR IN COMBINATION WITH
            OTHER INFORMATION AVAILABLE TO US. EXAMPLES OF PERSONAL DATA ARE A
            NAME, AN ONLINE IDENTIFIER, A CONTACT ADDRESS, SOCIAL MEDIA REVIEWS
            AND RATINGS, AND PRECISE LOCATION DATA. "NON-PERSONAL INFORMATION"
            MEANS INFORMATION THAT IS AGGREGATE, ANONYMOUS, PRACTICALLY
            DE-IDENTIFIED, OR OTHERWISE DOES NOT REVEAL YOUR IDENTITY. SOME
            EXAMPLES COULD INCLUDE AGE, ANNUAL INCOME, GENDER, BR/OWSER, IP
            ADDRESSES, HARDWARE MODEL, OPERATING SYSTEM AND VERSION, TIME SPENT
            USING OUR SERVICES, WEB PAGES VISITED, AND ADVERTISING IDENTIFIERS
            (SUCH AS THE APPLE IDENTIFIER FOR ADVERTISING (IDFA) AND GOOGLE
            ADVERTISING ID (AAID)).
            <br />
            <br />
            <br />
            WE COLLECT YOUR PERSONAL DATA AND NON-PERSONAL INFORMATION AS
            FOLLOWS:
            <br />
            <br />1 IF YOU REGISTER FOR A MAIDSIMPL ACCOUNT, INSTALL OR USE OUR
            MOBILE APPS, OR PLACE AN ORDER, WE COLLECT DIRECTLY OR INDIRECTLY
            (SUCH AS THROUGH A THIRD PARTY APPLICATION) CERTAIN REGISTRATION AND
            DEMOGRAPHIC DETAILS (E.G., NAME, USERNAME AND PASSWORD, EMAIL
            ADDRESS, PHONE NUMBER, DATE OF BIRTH, PERSONAL INTERESTS AND
            LOCATION (E.G., COUNTRY) AND OTHER SIMILAR DETAILS ("ACCOUNT
            INFORMATION").
            <br />
            <br />2 WHEN INTERACTING WITH OUR SERVICES, DATA IS AUTOMATICALLY
            COLLECTED BY THE TECHNOLOGY PLATFORMS PROVIDING THE EXPERIENCES,
            INCLUDING WITHOUT LIMITATION INFORMATION ABOUT THE SITES THAT YOU
            VISIT AN HOW YOU USE THEM AND ANY GPS-BASED, WI-FI-BASED, OR
            CELL-BASED LOCATION INFORMATION ("LOCATION INFORMATION"), AND ANY
            OTHER IDENTIFIER THAT PERMITS DIRECT IDENTIFYING, LOCATING, OR
            CONTACTING OF THE DEVICE OR USER. YOUR WEB BR/OWSER OR MOBILE DEVICE
            MAY SHARE CERTAIN DATA WITH MAIDSIMPL AS THOSE DEVICES INTERACT WITH
            MAIDSIMPL SITES OR MOBILE APPS. THIS DATA INCLUDES: DEVICE IDS,
            NETWORK ACCESS, STORAGE INFORMATION AND BATTERY INFORMATION AS WELL
            AS COOKIES, IP ADDRESSES, REFERRER HEADERS, DATA IDENTIFYING YOUR
            WEB BR/OWSER AND VERSION, THE DATE AND TIME OF THE VISIT AND HOW
            LONG YOU REMAINED ON OUR SITES, AND WEB BEACONS AND TAGS. LOCATION
            DATA MAY INCLUDE THE PRESENCE OF THE DEVICE, ITS SIGNAL STRENGTH AND
            MOBILE NETWORK INFORMATION, ITS MANUFACTURER (APPLE, SAMSUNG, ETC.)
            AND MODEL, AND INFORMATION ABOUT THE DEVICE'S INTERACTION WITH THE
            SERVICES OR BUSINESS SERVICES. MAIDSIMPL MAY COMBINE THIS
            INFORMATION WITH OTHER INFORMATION COLLECTED IN CONNECTION WITH YOUR
            USE OF THE SERVICES. MORE INFORMATION ABOUT THESE PRACTICES IS
            INCLUDED IN THE COOKIES AND OTHER DATA COLLECTION TOOLS SECTION
            BELOW.
            <br />
            <br />3 IF YOU ENGAGE WITH US THROUGH A SOCIAL MEDIA ACCOUNT, WE MAY
            COLLECT ACCOUNT OR PROFILE INFORMATION ASSOCIATED WITH THAT ACCOUNT.
            TO THE EXTENT YOU CONNECT AN ACCOUNT MANAGED BY THIRD PARTIES SUCH
            AS SOCIAL MEDIA SITES (E.G., FACEBOOK) WITH A MAIDSIMPL ACCOUNT, YOU
            AUTHORIZE MAIDSIMPL TO HAVE ACCESS TO INFORMATION RELATED TO THAT
            ACCOUNT (AS PERMITTED BY THE TERMS OF SERVICE OF YOUR ACCOUNT WITH
            THAT SOCIAL MEDIA SITE) AND AGREE THAT MAIDSIMPL MAY COLLECT, STORE
            AND USE SUCH INFORMATION IN ACCORDANCE WITH THIS POLICY.
            <br />
            <br />4 IF YOU ARE ACCESSING THIRD-PARTY PRODUCTS AND SERVICES THAT
            WE HAVE MADE AVAILABLE TO YOU VIA THE SERVICES, WE MAY COLLECT YOUR
            NAME, EMAIL ADDRESS, CITY, PAYMENT INFORMATION, AND MORE, IN
            CONNECTION WITH YOUR REGISTRATION FOR AND ACCESS TO THOSE PRODUCTS
            AND SERVICES.
            <br />
            <br />5 WHEN YOU PURCHASE OR BR/OWSE MAIDSIMPL PRODUCTS ONLINE, WE
            COLLECT PURCHASE AND BR/OWSING DATA. AS YOU BR/OWSE OUR PRODUCTS
            ONLINE OR SUBMIT PRODUCT INQUIRIES, WE MAY COLLECT PERSONAL DATA
            SUCH AS YOUR CONTACT INFORMATION AND YOUR SPECIFIC REQUESTS. WE ALSO
            MAY COLLECT INFORMATION REGARDING A COMPLETED PURCHASE (PAYMENT
            AMOUNTS AND METHODS, BILLING AND SHIPPING INFORMATION, RETURNS AND
            OTHER TRANSACTION INFORMATION). NON-PERSONAL INFORMATION RELATING TO
            YOUR BR/OWSING OF OUR PRODUCTS (SUCH AS BR/OWSING ORDER AND PRODUCTS
            REMOVED FROM A SHOPPING CART) MAY ALSO BE COLLECTED. WE MAY
            ASSOCIATE PURCHASE AND BR/OWSING INFORMATION TO AN ACCOUNT YOU HAVE
            REGISTERED WITH US AND COMBINE IT WITH INFORMATION RELATING TO ALL
            INTERACTIONS WITH US.
            <br />
            <br />6 WHEN YOU SHOP AT MAIDSIMPL POP-UP STORES, WE MAY COLLECT
            CONTACT AND PURCHASE INFORMATION. WHEN YOU ARE SHOPPING AT A
            MAIDSIMPL POP-UP STORE WE COLLECT ANY CONTACT AND PURCHASE
            INFORMATION THAT IS NECESSARY TO PROCESS YOUR TRANSACTION. FOR
            EXAMPLE, WE MAY COLLECT PAYMENT INFORMATION AND EMAIL ADDRESS (TO
            PROVIDE E-RECEIPTS). IN ADDITION, IF YOU CONSENT AND WHERE
            PERMISSIBLE, WE MAY COLLECT YOUR EMAIL AND PHONE NUMBER(S) IN ORDER
            TO SEND YOU INFORMATION ABOUT PRODUCTS AND PROMOTIONS.
            <br />
            <br />7 IF YOU PARTICIPATE IN OR UTILIZE, AS APPLICABLE, CONTESTS,
            SWEEPSTAKES, LOYALTY PROGRAMS, SURVEYS, DISCOUNTS, OR PROMOTIONAL
            SALES ("PROMOTIONS") BEING OFFERED BY MAIDSIMPL, WE MAY COLLECT
            CONTACT, DEMOGRAPHIC AND ELIGIBILITY INFORMATION OR OTHER PERSONAL
            DATA. IN SUCH INSTANCES, PERSONAL DATA MAY BE COLLECTED DIRECTLY BY
            AND/OR SHARED WITH MAIDSIMPL, THE SERVICE PROVIDER AND/OR BUSINESS
            PARTNER VIA PRINT, WEBSITE, MOBILE APPLICATIONS OR OTHER MEANS.
            PERSONAL DATA ASSOCIATED WITH A PROMOTION MAY BE SHARED WITH
            PARTNERS THAT SPONSORED OR WERE INVOLVED WITH THE PROMOTI ON.
            <br />
            <br />8 WE COLLECT PERSONAL DATA RELATING TO YOUR INTERACTIONS WITH
            ADVERTISING ON THE SERVICES OR MAIDSIMPL ONLINE COMMUNITIES. WE MAY
            COLLECT YOUR PERSONAL DATA WHEN YOU CLICK ON ADVERTISEMENTS, SUBMIT
            CONTENT, MAKE REVIEWS, INTERACT WITH OUR SOCIAL MEDIA PAGES, OR
            OTHERWISE CONTRIBUTE TO MESSAGE BOARDS, COMMENT FIELDS, BLOGS, AND
            OTHER MEDIA FORUMS SPONSORED BY OR AFFILIATED WITH MAIDSIMPL.
            <br />
            <br />9 WE ALLOW OUR TRUSTED AD PARTNERS TO COLLECT INFORMATION
            ABOUT YOU WHEN YOU USE OUR SERVICES. THESE COMPANIES MAY COLLECT
            INFORMATION FROM YOU (E.G. SUBJECT OF ADVERTISEMENTS CLICKED OR
            SCROLLED OVER) DURING YOUR VISITS TO THE SERVICES IN ORDER TO
            PROVIDE ADVERTISEMENTS ABOUT GOODS AND SERVICES LIKELY TO BE OF
            INTEREST TO YOU. OUR AD PARTNERS MAY USE THE DATA THEY COLLECT FROM
            YOU FOR A VARIETY OF OTHER PURPOSES, INCLUDING (A) IN CONJUNCTION
            WITH ADVERTISING THAT APPEARS ON OTHER WEBSITES, (B) TO DETERMINE
            THE POPULARITY OF CERTAIN CONTENT AND ANALYZE AND TRACK WEBSITE
            TRAFFIC, STATISTICS, ADVERTISEMENT DATA AND OTHER INTERACTION WITH
            ADS AND THE WEBSITES ON WHICH THEY ARE SERVED, AND (C) TO MEASURE
            THE EFFECTIVENESS OF WEB-BASED AND EMAIL ADS. THE AD PARTNERS THAT
            WE ENGAGE ARE BOUND BY CONFIDENTIALITY OBLIGATIONS AND OTHER
            RESTRICTIONS WITH RESPECT TO THEIR USE AND COLLECTION OF YOUR
            INFORMATION.
            <br />
            <br /> HOW WE USE YOUR INFORMATION
            <br />
            WE USE THE INFORMATION WE COLLECT TO:
            <br />
            <br />1 PROVIDE OUR PRODUCTS AND SERVICES AND CUSTOMER SUPPORT.
            <br />
            <br />
            WE USE PERSONAL DATA AND NON-PERSONAL DATA TO PROCESS AND DELIVER
            PRODUCT ORDERS AND TO NOTIFY YOU OF THE STATUS OF YOUR ORDER.
            ADDITIONALLY, THIS DATA MAY BE USED TO TROUBLESHOOT PROBLEMS WITH
            YOUR EXPERIENCE WITH THE SERVICES. IF YOU CONTACT OUR CUSTOMER
            SERVICE (OR VICE VERSA), WE WILL USE PERSONAL DATA SUCH AS YOUR
            ORDER INFORMATION AND CONTACT HISTORY TO PROCESS YOUR REQUEST AND
            PROVIDE YOU WITH THE BEST SERVICE POSSIBLE.
            <br />
            <br />2 CUSTOMIZE EXPERIENCES ON OUR SERVICES AND GAIN INSIGHTS INTO
            OUR CUSTOMERS AND COMMUNITIES.
            <br />
            <br />
            WE USE PERSONAL DATA AND NON-PERSONAL DATA TO PRESENT PRODUCTS AND
            CONTENT TAILORED TO YOU, YOUR INTERESTS AND LOCATION. OUR USE OF
            PERSONAL DATA MAY ALSO HELP YOU ENGAGE WITH OTHER USERS OF OUR
            SERVICES. WE ALSO USE PERSONAL DATA TO BETTER UNDERSTAND OUR
            CUSTOMERS AND OTHER INDIVIDUALS WHO ACCESS OUR SERVICES WHICH HELPS
            US DEVELOP MORE INTERESTING AND RELEVANT PRODUCTS AND SERVICES AND
            TO IMPROVE OUR SERVICES.
            <br />
            <br />3 PROMOTE MAIDSIMPL'S BUSINESS THROUGH DIRECT MAIL AND ONLINE
            ADVERTISING AND MARKETING ACTIVITIES TO YOU AND OTHERS.
            <br />
            <br />
            WE USE PERSONAL DATA AND NON-PERSONAL INFORMATION IN CONNECTION WITH
            ADVERTISING AND ONLINE AND OFFLINE MARKETING CAMPAIGNS, TO PROVIDE
            YOU WITH INFORMATION ON THE PRODUCTS AND SERVICES THAT WE THINK ARE
            MOST RELEVANT TO OR APPROPRIATE FOR YOU AND TO TRACK THE SUCCESS OF
            OUR MARKETING ACTIVITIES. WE DISPLAY ADS ON THE ONLINE PLATFORMS
            THAT WE OWN AND OPERATE. WE ALSO USE THIRD PARTY AD PARTNERS TO
            DISPLAY ADS FOR MAIDSIMPL ON THIRD PARTY WEBSITES AND APPS
            ("RETARGETING"). RETARGETING TECHNOLOGIES ANALYZE THE INFORMATION
            COLLECTED ABOUT YOUR INTERACTIONS WITH MAIDSIMPL SITES AS DESCRIBED
            IN RELATION TO MARKETING ABOVE AND INFORMATION ABOUT YOU OBTAINED
            FROM REPUTABLE THIRD PARTY SOURCES PARTIES, INCLUDING YOUR COOKIES,
            AND DISPLAY ADVERTISEMENTS MATCHED TO YOUR INTERESTS, AS INFERRED
            FROM YOUR ONLINE ACTIVITIES. ADS MAY ALSO BE BASED ON THE CONTENT OF
            THE PAGES ON WHICH THEY APPEAR AND LOCATION DATA MAY BE USED TO
            SERVE ADS THAT ARE MORE RELEVANT TO YOU BASED ON YOUR PARTICULAR
            LOCATION. FOR MOST DEVICES, YOU CAN CONTROL THE INTEREST- BASED ADS
            YOU SEE AS A RESULT OF RETARGETING BY CHANGING THE PRIVACY SETTINGS
            OF THE DEVICE ITSELF OR CHANGING THE PRIVACY SETTINGS OF YOUR
            BR/OWSER BUT NOTE THAT OUR SITES GENERALLY ARE NOT CONFIGURED TO
            RESPOND TO WEB BR/OWSER DO-NOT-TRACK SIGNALS.
            <br />
            <br />4 CONNECT YOU WITH THIRD-PARTY PRODUCTS AND SERVICES.
            <br />
            <br />
            WE USE THE DATA WE COLLECT TO PROVIDE THIRD PARTIES WITH THE
            INFORMATION REQUIRED TO ENABLE THOSE THIRD PARTIES TO FULFILL
            PRODUCTS OR SERVICES THAT A MAIDSIMPL USER HAS ORDERED.
            <br />
            <br />5 COMMUNICATE WITH YOU.
            <br />
            <br />
            IF YOU HAVE CREATED AN ACCOUNT WITH US, AND CONSENT TO RECEIVING
            MESSAGES FROM US VIA ELECTRONIC COMMUNICATIONS, WE MAY USE PERSONAL
            DATA AND NON-PERSONAL INFORMATION TO CONTACT YOU ABOUT THE MAIDSIMPL
            PRODUCTS OR SERVICES YOU HAVE PURCHASED OR USED AND TO NOTIFY YOU OF
            OTHER PRODUCTS, PROMOTIONS AND SERVICES WE THINK MAY BE OF INTEREST
            TO YOU. WE MAY USE YOUR INFORMATION TO RESPOND TO REQUESTS FOR
            SUPPORT, ONLINE SERVICES, PRODUCT INFORMATION OR TO ANY OTHER
            INTERACTION YOU INITIATE. WE ALSO MAY USE YOUR PERSONAL DATA TO
            NOTIFY YOU OF PROMOTIONS AND OTHER SPECIAL OFFERS. IRRESPECTIVE OF
            YOUR PRIVACY SETTINGS, WE MAY SEND YOU NOTIFICATIONS PERTAINING TO
            THE PERFORMANCE OF OUR SERVICES, SUCH AS REVISION OF OUR TERMS OR
            THIS PRIVACY POLICY OR OTHER FORMAL COMMUNICATIONS RELATING TO
            PRODUCTS OR SERVICES YOU HAVE PURCHASED OR USE.
            <br />
            <br />6 ADMINISTER PROMOTIONS.
            <br />
            <br />
            IN CONNECTION WITH PROMOTIONS WE MAY USE PERSONAL DATA TO VERIFY
            IDENTITY, COMMUNICATE WITH YOU ABOUT THE PROMOTION OR ABOUT OTHER
            OFFERS, CONDUCT MARKET RESEARCH, AND ASK YOU QUESTIONS RELATING TO
            THE PROMOTION. IF YOU PARTICIPATE IN QUESTIONS AND SURVEYS REGARDING
            THE PROMOTION WE MAY SHARE YOUR RESPONSES WITH BUSINESS PARTNERS FOR
            THEIR OWN MARKET RESEARCH AND COMMUNICATION PURPOSES. TO OPT-OUT OF
            THIS KIND OF COLLECTION AND SHARING, YOU CAN DECLINE TO ANSWER THESE
            KINDS OF QUESTIONS OR DECLINE TO PARTICIPATE IN THE CHALLENGE OR
            SURVEY ALTOGETHER.
            <br />
            <br />7 OPERATE AND ANALYZE OUR BUSINESS.
            <br />
            <br />
            WE USE PERSONAL DATA AND NON-PERSONAL INFORMATION TO ANALYZE TRENDS
            AND STATISTICS AND OTHERWISE MONITOR USAGE AND PERFORMANCE OF THE
            SERVICES, ENGAGE IN BUSINESS TRANSACTIONS, INCLUDING THE PURCHASE,
            SALE, LEASE, MERGER, AMALGAMATION OR ANY OTHER TYPE OF ACQUISITION,
            DISPOSAL, SECURITIZATION OR FINANCING INVOLVING MAIDSIMPL, COMPLY
            WITH ANY APPLICABLE LEGAL OR REGULATORY REQUIREMENTS, AND FOR SALES,
            SUPPLY CHAIN AND FINANCIAL ANALYSIS PURPOSES.
            <br />
            <br />8 RESOLVE SECURITY ISSUES AND DISPUTES.
            <br />
            <br />
            WE USE THE DATA WE COLLECT FROM YOU TO PROTECT THE INTEGRITY OF OUR
            SERVICES, EMPLOYEES AND USERS, TO IDENTIFY AND PREVENT ERROR,
            NEGLIGENCE AND FRAUD, TO AUDIT COMPLIANCE WITH AND ENFORCE OUR
            AGREEMENTS (SUCH AS TERMS OF USE, TERMS OF SALE AND THIS PRIVACY
            POLICY), AND TO RESOLVE DISPUTES.
            <br />
            <br />9 WE MAY AUGMENT PERSONAL DATA WE COLLECT FROM YOU WITH
            INFORMATION PROVIDED BY REPUTABLE THIRD PARTY SOURCES.
            <br />
            <br />
            WE MAY COMBINE PERSONAL DATA WITH INFORMATION WE RECEIVE FROM JOINT
            MARKETING PARTNERS, PUBLIC DATABASES, PUBLICLY AVAILABLE PAGES ON
            SOCIAL MEDIA PLATFORMS AND OTHER THIRD PARTIES, TO GIVE US BETTER
            CONSUMER INSIGHT INTO YOUR NEEDS, HELP US TAILOR OUR COMMUNICATIONS
            WITH YOU, DELIVER MARKETING MESSAGES TO YOU AND IMPROVE OUR
            BUSINESS. FOR EXAMPLE, WE MAY OBTAIN UPDATED EMAIL ADDRESS
            INFORMATION FROM EMAIL-CHANGE-OF- ADDRESS VENDORS OR PURCHASE
            THIRD-PARTY MARKETING DATA AND ADDRESS INFORMATION AND ADD IT TO OUR
            DATABASE TO SEND YOU OFFLINE MARKETING MATERIALS, BETTER DIRECT OUR
            ADVERTISING AND PROVIDE PERTINENT OFFERS WE THINK YOU ARE MORE
            LIKELY TO BE INTERESTED IN. YOU CAN OPT-OUT OF US COMBINING YOUR
            PERSONAL INFORMATION WITH THE INFORMATION LAWFULLY COLLECTED FROM
            THIRD PARTIES BY CONTACTING US USING THE CONTACT DETAILS SET OUT
            BELOW.
            <br />
            <br />
            III. HOW WE SHARE YOUR INFORMATION
            <br />
            <br />
            MAIDSIMPL WILL SHARE YOUR PERSONAL DATA AND NON-PERSONAL INFORMATION
            WITH THIRD PARTIES IN THE FOLLOWING WAYS:
            <br />
            <br />1 TO PARTNERS AND SUPPLIERS.
            <br />
            <br />
            MAIDSIMPL MAY (A) COORDINATE THE PROVISION OF SERVICES AND PRODUCTS
            TO YOU THROUGH THIRD PARTY SERVICE PROVIDERS AND (B) PARTNER WITH
            THIRD PARTIES IN ORDER TO PROMOTE, SUPPORT, ENABLE OR EXPAND
            MAIDSIMPL BUSINESS AND PRODUCTS AND SERVICES OR ENABLE THOSE THIRD
            PARTIES TO DELIVER CONTENT OR ADVERTISE THE PRODUCTS AND SERVICES OF
            MAIDSIMPL. WE MAY SHARE PERSONAL DATA WITH THOSE SERVICE PROVIDERS
            AND PARTNERS AND THEY MAY HAVE ACCESS TO OR PROCESS YOUR PERSONAL
            DATA. FOR EXAMPLE, MAIDSIMPL MAY USE THIRD-PARTY PROVIDERS TO ASSIST
            US WITH DELIVERING, MARKETING AND ADVERTISING OUR PRODUCTS AND
            SERVICES, PROCESSING PAYMENTS YOU MAKE TO US, DELIVERING CUSTOMER
            SERVICE AND SUPPORT, AND FOR E-COMMERCE ORDER FULFILLMENT. IN
            ADDITION, WITH YOUR KNOWLEDGE AND CONSENT, OUR SERVICES MAY GATHER
            AND TRANSFER INFORMATION FROM OTHER APPLICATIONS, FUNCTIONS AND
            TOOLS WITHIN YOUR MOBILE DEVICE.
            <br />
            <br />3 WITH SOCIAL NETWORKS.
            <br />
            <br />
            OUR SITES AND APPS WILL, IN CERTAIN CIRCUMSTANCES, PROVIDE YOU WITH
            SOCIAL PLUG-INS FROM VARIOUS SOCIAL NETWORKS. IF YOU CHOOSE TO
            INTERACT WITH A SOCIAL NETWORK SUCH AS FACEBOOK OR TWITTER (FOR
            EXAMPLE BY REGISTERING AN ACCOUNT), YOUR ACTIVITY ON SITES OR VIA
            OUR APPS WILL ALSO BE MADE AVAILABLE TO THAT SOCIAL NETWORK.
            <br />
            <br />4 FOR JOINT MARKETING.
            <br />
            <br />
            FROM TIME TO TIME, MAIDSIMPL MIGHT ESTABLISH JOINT MARKETING
            RELATIONSHIPS WITH OTHER PERSONS OR ENTITIES WHOM WE BELIEVE
            TRUSTWORTHY AND HAVE PRIVACY PRACTICES THAT ARE CONSISTENT WITH
            OURS. IN SUCH CASES AND WHERE PERMITTED BY APPLICABLE LAW WE MIGHT
            EXCHANGE, SHARE AND/OR CROSS-REFERENCE INFORMATION, INCLUDING
            INFORMATION ABOUT YOU THAT WILL ENABLE SUCH PERSONS OR ENTITIES TO
            CONTACT YOU REGARDING PRODUCTS AND SERVICES THAT MAY BE OF INTEREST
            TO YOU. IF YOU WOULD LIKE TO OPT OUT OF OUR EXCHANGE OF YOUR
            INFORMATION WITH OTHER MARKETERS, PLEASE LET US KNOW BY WRITING TO
            OUR SUPPORT TEAM.
            <br />
            <br />5 IN DISCUSSION FORUMS.
            <br />
            <br />
            CONTENT YOU POST THROUGH THE SERVICES SUCH AS REVIEWS, COMMENTARY ON
            DISCUSSION BOARDS OR BLOGS, AND CERTAIN SOCIAL NETWORKING
            PREFERENCES (E.G. PAGES YOU "LIKE" OR "RECOMMEND") MAY BE ACCESSIBLE
            BY OTHER USERS AND COMPANIES AND MAY APPEAR ON OTHER WEBSITES OR WEB
            SEARCHES, AND THEREFORE THIS INFORMATION COULD BE READ, COLLECTED,
            AND USED BY OTHERS. MAIDSIMPL CANNOT ENSURE THE PRIVACY OF ANY
            PERSONAL DATA INCLUDED IN SUCH USER GENERATED CONTENT. PLEASE NOTE
            THAT MAIDSIMPL DOES NOT NECESSARILY VERIFY, ENDORSE, OR AGREE WITH
            ANY CONTENT POSTED IN DISCUSSION FORUMS.
            <br />
            <br />6 IN BUSINESS TRANSFERS (COUNTRY SPECIFIC DISCLOSURES MAY
            APPLY).
            <br />
            <br />
            IN THE EVENT THAT MAIDSIMPL SELLS CERTAIN OF ITS ASSETS OR GOES
            THROUGH A STRUCTURAL CHANGE, SUCH AS A MERGER, ACQUISITION BY
            ANOTHER COMPANY, BANKRUPTCY, INSOLVENCY, OR DISSOLUTION, TO THE
            EXTENT PERMITTED BY APPLICABLE LAW PERSONAL DATA MAY BE TRANSFERRED
            TO A THIRD PARTY AS PART OF SUCH EVENT AND THEREBY BECOME SUBJECT TO
            THE PRIVACY PRACTICES OF THAT THIRD PARTY, WHICH MAY MATERIALLY
            DIFFERENT THAN THOSE OF MAIDSIMPL.
            <br />
            <br />7 WITH YOUR CONSENT.
            <br />
            <br />
            MAIDSIMPL WILL SHARE YOUR PERSONAL DATA WITH OTHER THIRD PARTIES
            (DIFFERENT FROM THOSE DESCRIBED IN THIS SECTION) IN CERTAIN LIMITED
            CIRCUMSTANCES. IN THESE INSTANCES WE WILL, TO THE EXTENT REQUIRED BY
            APPLICABLE LAW, OBTAIN YOUR CONSENT TO SHARE YOUR PERSONAL DATA IN
            THIS WAY.
            <br />
            <br />8 FOR LEGAL COMPLIANCE AND SPECIAL CIRCUMSTANCES.
            <br />
            <br />
            WE MAY BE REQUIRED, SUBJECT TO APPLICABLE LAW, TO DISCLOSE YOUR
            PERSONAL DATA IF: (1) IT IS REASONABLY NECESSARY TO COMPLY WITH
            LEGAL PROCESS (SUCH AS A COURT ORDER, SUBPOENA, SEARCH WARRANT,
            ETC.) OR OTHER LEGAL REQUIREMENTS OF ANY GOVERNMENTAL AUTHORITY,
            (II) SUCH A DISCLOSURE WOULD POTENTIALLY MITIGATE OUR LIABILITY IN
            AN ACTUAL OR POTENTIAL LAWSUIT, (III) IT IS NECESSARY TO PROTECT OUR
            LEGAL RIGHTS OR PROPERTY (SUCH AS ENFORCING OR APPLYING APPLICABLE
            TERMS AND CONDITIONS AND OTHER AGREEMENTS, INCLUDING THE SERVICES'
            TERMS OF SERVICE), OR (IV) IT IS NECESSARY TO PROTECT THE LEGAL
            RIGHTS OR PROPERTY OR PHYSICAL SECURITY OF OTHERS, OR FOR THE
            PREVENTION OR DETECTION OF CRIME AND SUCH DISCLOSURE IS LAWFUL.
            <br />
            <br />
            DATA SECURITY
            <br />
            MAIDSIMPL TAKES PRECAUTIONS TO SECURE YOUR PERSONAL INFORMATION AND
            PROTECT IT FROM LOSS, THEFT, UNAUTHORIZED ACCESS, DESTRUCTION, USE,
            MODIFICATION AND DISCLOSURE. SUCH MEASURES INCLUDE TECHNOLOGICAL,
            PHYSICAL AND ORGANIZATIONAL SAFEGUARDS THAT ARE APPROPRIATE GIVEN
            THE SENSITIVITY OF THE PERSONAL INFORMATION, INCLUDING MAINTAINING
            CONTROLLED ACCESS TO ELECTRONIC AND PAPER DOCUMENTS AND FILES, AND
            USING APPROPRIATE TECHNOLOGY SAFEGUARDS SUCH AS PASSWORDS FIREWALLS
            AND ENCRYPTION AS WELL AS NON-DISCLOSURE OR CONFIDENTIALITY
            AGREEMENTS AS WE DEEM APPROPRIATE TO PROTECT YOUR DATA. HOWEVER,
            PLEASE NOTE THAT MAIDSIMPL'S SECURITY MEASURES MAY CHANGE OR BE
            UNAVAILABLE FROM TIME TO TIME AND NO DATA TRANSMISSION OVER THE
            INTERNET OR ANY WIRELESS NETWORK IS 100% SECURE.
            <br />
            <br />
            DATA RETENTION
            <br />
            MAIDSIMPL WILL RETAIN PERSONAL DATA FOR SO LONG AS IT CONTINUES TO
            BE USEFUL IN CONNECTION WITH PROVIDING OR IMPROVING MAIDSIMPL'S
            SERVICES AND PRODUCT OFFERINGS AND THIS POLICY, EXCEPT IF REQUIRED
            OTHERWISE BY APPLICABLE LAW. WE MAY FURTHER RETAIN AND USE DATA AS
            NECESSARY TO COMPLY WITH OUR LEGAL OBLIGATIONS, RESOLVE DISPUTES,
            AND ENFORCE OUR AGREEMENTS.
            <br />
            <br />
            COOKIES AND OTHER DATA COLLECTION TOOLS
            <br />
            MAIDSIMPL AND ITS PARTNERS USE VARIOUS TECHNOLOGIES TO COLLECT
            INFORMATION WHEN YOU USE OUR SERVICES, INCLUDING SENDING COOKIES TO
            YOUR DEVICE AND USING WEB BEACONS. BY USING THE SERVICES YOU CONSENT
            TO THE USE OF SUCH TECHNOLOGIES, INCLUDING COOKIES AND PIXEL TAGS,
            TO COLLECT INFORMATION ABOUT YOU. THESE TECHNOLOGIES HELP US
            PERSONALIZE YOUR USE OF OUR SITES AND MOBILE APPLICATIONS, CUSTOMIZE
            THE SERVICES, AND MITIGATE RISKS AND THE POTENTIAL FOR FRAUD. THESE
            TECHNOLOGIES ARE ALSO USED BY MAIDSIMPL AND ITS ADVERTISING PARTNERS
            TO DELIVER ADS TO YOU BASED ON YOUR INTERESTS AND ONLINE ACTIVITIES.
            <br />
            <br />1 HOW WE USE COOKIES.
            <br />
            <br />
            WHEN YOU ACCESS OR USE THE SERVICES, OUR WEB SERVER MAY SEND A
            COOKIE TO YOUR DEVICE. "COOKIES" ARE SMALL DATA FILES PLACED ON A
            DEVICE'S HARD DRIVE OR MEMORY WHEN YOU INTERACT WITH A WEBSITE OR
            VIEW A MESSAGE. AMONG OTHER THINGS, COOKIES SUPPORT THE INTEGRITY OF
            OUR REGISTRATION PROCESS, RETAIN YOUR PREFERENCES AND ACCOUNT
            SETTINGS, AND HELP EVALUATE AND COMPILE AGGREGATED STATISTICS ABOUT
            USER ACTIVITY. WE MAY USE COOKIES TO: • REMEMBER THAT YOU HAVE
            VISITED US OR USED THE SERVICES BEFORE AND PERSONALIZE OUR CONTENT
            FOR YOU AND REMEMBER YOUR PREFERENCES (FOR EXAMPLE, YOUR CHOICE OF
            LANGUAGE OR REGION).
            <br />
            <br />• ENSURE WE HAVE ENOUGH CAPACITY TO ACCOMMODATE ALL OF OUR
            USERS AND THAT USERS ARE FINDING WHAT THEY ARE LOOKING FOR EASILY
            AND DO NOT ENCOUNTER TECHNICAL ERRORS.
            <br />
            <br />• COLLECT ANONYMOUS STATISTICAL INFORMATION ABOUT HOW YOU USE
            THE SERVICES (INCLUDING THE LENGTH OF YOUR WEB OR APPLICATION
            SESSION) AND THE LOCATION FROM WHICH YOU ACCESS THE SERVICES, SO
            THAT WE CAN IMPROVE THE SERVICES AND LEARN WHICH ELEMENTS AND
            FUNCTIONS OF THE SERVICES ARE MOST POPULAR WITH OUR USERS
            <br />
            <br />• HELPS US AND OUR AD PARTNERS TO DELIVER ADS OR MESSAGES THAT
            ARE RELEVANT TO YOU AND YOUR INTERESTS. WE MAY ALSO SHARE THIS
            INFORMATION WITH THIRD PARTIES FOR THIS PURPOSE. FOR EXAMPLE, THESE
            COOKIES ALLOW US TO IDENTIFY AND SEND YOU MESSAGES ABOUT ITEMS YOU
            HAVE LEFT IN YOUR CART AND MAKE OTHER PURCHASING RECOMMENDATIONS.
            <br />
            <br />2 WE USE THIRD-PARTY COOKIES.
            <br />
            <br />
            WE MAY ALLOW THIRD PARTIES TO COLLECT INFORMATION VIA THE SERVICES
            THROUGH COOKIES, THIRD PARTY PLUG-INS AND WIDGETS. THIRD PARTY
            COOKIES ENABLE THIRD PARTY FEATURES OR FUNCTIONALITY TO BE PROVIDED
            ON OR THROUGH THE SITES (E.G., WE MAY USE GOOGLE ANALYTICS AND
            GOOGLE ADWORDS TO COLLECT AND PROCESS CERTAIN ANALYTICS DATA).
            <br />
            <br />3 HOW WE USE WEB BEACONS.
            <br />
            <br />
            SOME OF OUR WEBSITES AND SERVICES MAY CONTAIN ELECTRONIC IMAGES
            CALLED "WEB BEACONS". WEB BEACONS ARE OBJECTS EMBEDDED IN A WEB PAGE
            OR EMAIL WHICH ARE USED TO CHECK IF A USER HAS ACCESSED CONTENT. IN
            ADDITION TO ALLOWING US TO COUNT HOW MANY PERSONS READ OUR MESSAGES,
            WEB BEACONS ALLOW US TO DEVELOP STATISTICAL INFORMATION ABOUT THE
            ACTIVITIES AND FEATURES THAT MOST INTEREST OUR USERS IN ORDER TO
            PROVIDE MORE PERSONALIZED CONTENT.
            <br />
            <br />4 DO NOT TRACK BR/OWSER SIGNALS.
            <br />
            <br />
            DO NOT TRACK ("DNT") IS AN OPTIONAL BR/OWSER SETTING THAT ALLOWS YOU
            TO EXPRESS YOUR PREFERENCES REGARDING TRACKING ACROSS WEBSITES.
            UNLESS REQUIRED BY APPLICABLE LAW OUR SITES ARE NOT GENERALLY
            CONFIGURED TO RESPOND TO DNT SIGNALS. WE AND THIRD PARTIES OPERATING
            ON THE SERVICES MAY CONTINUE TO COLLECT INFORMATION IN THE MANNER
            DESCRIBED IN THIS PRIVACY POLICY FROM WEB BR/OWSERS THAT HAVE
            ENABLED DNT SIGNALS OR SIMILAR MECHANISMS.
            <br />
            <br />
            VII. HOW TO MANAGE YOUR PRIVACY SETTINGS
            <br />
            <br />
            WE PROVIDE YOU SEVERAL WAYS TO MANAGE YOUR PRIVACY SETTINGS:
            <br />
            <br />1 UPDATE YOUR ACCOUNT INFORMATION IF YOUR ACCOUNT INFORMATION
            CHANGES, YOU MAY UPDATE OR DELETE AND DEACTIVATE CERTAIN ASPECTS OF
            YOUR ACCOUNT INFORMATION BY SIGNING INTO AND MANAGING YOUR MAIDSIMPL
            ACCOUNT OR, IF YOUR ACCOUNT DOES NOT SO PERMIT, BY CONTACTING US AT
            SUPPORT@MAIDSIMPL.COM. IN ADDITION, DEPENDING ON THE NATURE OF YOUR
            ACCOUNT, YOUR ACCOUNT MANAGEMENT PAGE MAY ALLOW YOU TO CONTROL
            CERTAIN ASPECTS OF HOW OTHER INFORMATION YOU SUBMIT TO THE SERVICES
            IS USED OR SHARED.
            <br />
            <br />2 SET YOUR PREFERENCES TO OPT-OUT OF COMMUNICATIONS. THERE ARE
            SEVERAL WAYS FOR YOU TO CONTROL HOW MAIDSIMPL COMMUNICATES WITH YOU:
            <br />
            <br />• EMAIL AND MOBILE MESSAGES: YOU HAVE THE ABILITY TO
            UNSUBSCRIBE TO PROMOTIONAL EMAILS OR TEXT MESSAGES RECEIVED FROM US
            BY FOLLOWING THE INSTRUCTIONS IN THOSE EMAILS OR TEXT MESSAGES. IF
            YOU USE MORE THAN ONE SERVICE THEN OPTING OUT OF THE EMAILS RELATING
            TO THAT SERVICE WILL NOT NECESSARILY STOP YOU RECEIVING EMAILS FROM
            OTHER SERVICES.
            <br />
            <br />• PUSH NOTIFICATIONS: TO THE EXTENT APPLICABLE YOU CAN MANAGE
            THE TYPE OF PUSH NOTIFICATIONS YOU RECEIVE FROM MAIDSIMPL (IF ANY)
            BY MODIFYING THE SETTINGS OF YOUR MAIDSIMPL APPLICATIONS AND
            WEBSITES. YOU MAY SET YOUR MOBILE DEVICE TO NOT ALLOW PUSH
            NOTIFICATIONS FROM US.
            <br />
            <br />• POSTAL MAIL: YOU MAY STOP RECEIVING MARKETING MATERIALS SENT
            BY POSTAL MAIL FROM US BY WRITING TO OUR SUPPORT TEAM OR FOLLOWING
            THE OPT-OUT INSTRUCTIONS THAT MAY BE INCLUDED WITHIN THOSE
            COMMUNICATIONS.
            <br />
            <br />3 MANAGE YOUR LOCATION.
            <br />
            <br />
            MOST MOBILE DEVICES GIVE USERS THE ABILITY TO CONTROL WHETHER
            LOCATION SIGNALS ARE ENABLED. DISABLING LOCATION SIGNALS WILL NOT
            ALLOW US TO COLLECT YOUR LOCATION DATA (BY VIRTUE OF THE LOCATION OF
            YOUR MOBILE DEVICE) AND MAY IMPACT THE OPERATION OF A SERVICE. IF
            YOU HAVE QUESTIONS ABOUT HOW TO SET THE LOCATION PREFERENCES FOR
            YOUR DEVICE, YOU CAN CONTACT YOUR MOBILE SERVICE CARRIER OR YOUR
            DEVICE MANUFACTURER.
            <br />
            <br />
            IF YOU UNSUBSCRIBE TO EMAIL MARKETING MESSAGES IT MAY TAKE UP TO 10
            BUSINESS DAYS BEFORE YOU STOP RECEIVING EMAILS AND WE MAY STILL SEND
            YOU NON-PROMOTIONAL COMMUNICATIONS, SUCH AS DIGITAL RECEIPTS (IF
            APPLICABLE) AND COMMUNICATIONS ABOUT YOUR ACCOUNT. REQUESTS TO STOP
            OR UPDATE POSTAL MAIL MARKETING COMMUNICATIONS MAY TAKE UP 6-8 WEEKS
            TO PROCESS. VIII. CHILDREN
            <br />
            <br />
            THE SERVICES ARE INTENDED FOR GENERAL AUDIENCES AND IS NOT DIRECTED
            TO PERSONS LESS THAN 13 YEARS OF AGE AND WE DO NOT KNOWINGLY COLLECT
            PERSONAL DATA FROM THOSE PERSONS. IF YOU BECOME AWARE THAT PERSONAL
            INFORMATION ABOUT YOUR CHILD HAS BEEN PROVIDED TO MAIDSIMPL WITHOUT
            YOUR CONSENT, PLEASE CONTACT US. IF WE BECOME AWARE THAT A CHILD
            UNDER 13 HAS PROVIDED US WITH PERSONAL DATA, WE WILL TAKE STEPS TO
            DELETE THE INFORMATION, EXCEPT WHERE WE ARE REQUIRED BY APPLICABLE
            LAW TO KEEP IT.
            <br />
            <br />
            THIRD PARTIES WE DON'T OWN OR CONTROL
            <br />
            <br />
            THIS PRIVACY POLICY DOES NOT APPLY TO THE PRACTICES OF COMPANIES
            THAT WE DO NOT OWN OR CONTROL OR TO PEOPLE THAT WE DO NOT EMPLOY OR
            MANAGE. FOR EXAMPLE, IF YOU CHOOSE TO PAY THROUGH A THIRD-PARTY
            MECHANISM OFFERED ON OUR WEBSITE, THE INFORMATION YOU CHOOSE TO
            SHARE WITH THAT THIRD-PARTY WILL BE TREATED IN ACCORDANCE WITH THAT
            THIRD-PARTY'S PRIVACY POLICY. THIS POLICY DOES NOT APPLY TO, AND WE
            ARE NOT RESPONSIBLE FOR, FOR THE CONTENT OF SUCH THIRD PARTY
            FEATURES OR THE PRIVACY PRACTICES, INCLUDING THIRD- PARTY COOKIES,
            WEB BEACONS, OR OTHER TRACKING TECHNOLOGIES, OF SUCH THIRD PARTIES.
            WE ENCOURAGE YOU TO READ THE PRIVACY POLICIES OF EACH AND EVERY
            DEVICE, WEBSITE, AND SERVICE THAT YOU USE.
            <br />
            <br />
            HOW TO CONTACT US
            <br />
            <br />
            MAIDSIMPL WELCOMES QUESTIONS AND COMMENTS ABOUT THIS PRIVACY POLICY.
            YOU CAN CONTACT US BY EMAILING US AT SUPPORT@MAIDSIMPL.COM.
            <br />
            <br />
            XII. AMENDMENTS
            <br />
            <br />
            WE MAY CHANGE THIS POLICY FROM TIME TO TIME. THE MOST CURRENT
            VERSION OF THIS POLICY WILL BE EFFECTIVE AT THE TIME IT IS POSTED.
            BY CONTINUING TO ACCESS OR USE THE SERVICES AFTER THOSE CHANGES
            BECOME EFFECTIVE, YOU AGREE TO BE BOUND BY THE REVISED POLICY. IF
            YOU HAVE A REGISTERED ACCOUNT, WE MAY NOTIFY YOU OF ANY CHANGES TO
            OUR PRIVACY POLICY VIA EMAIL AND/OR WE MAY ASK YOU TO AFFIRMATIVELY
            ACKNOWLEDGE AND CONSENT TO THE CHANGES THE NEXT TIME YOU USE OUR
            SERVICES.
          </div>
        </div>
      </div>
    </div>
  );
};

export default Privacy;
