import React from "react";
import { useContext } from "react";
import { GlobalContext } from "../context/GlobalContext";

const Privacy = () => {
  const { palette } = useContext(GlobalContext);
  return (
    <div className="w-full h-auto flex flex-col justify-start items-start">
      <div className="w-full h-auto  flex flex-col justify-start items-center px-2 md:px-10 py-2 md:py-6 lg:py-8 mt-10 gap-4 my-16 lg:gap-8">
        <div className="w-full h-auto flex flex-col gap-2 items-center justify-center">
          <h1
            className="text-4xl  font-bold  "
            style={{ color: palette?.brand }}
          >
            Privacy Policy
          </h1>
          <p>
            <strong>Updated at January 1st, 2024</strong>
          </p>
        </div>

        <div className="w-full lg:w-[90%] h-auto px-0 lg:px-20 relative">
          <div className="w-full h-auto z-[1000] rounded-3xl flex flex-col gap-3 justify-start items-start  text-md font-medium bg-gray-50 p-6 lg:p-10 ">
            <p>
              <strong>Now You Know Nashville</strong> ("we," "our," or "us") is
              committed to protecting your privacy. This Privacy Policy explains
              how your personal information is collected, used, and disclosed by
              Now You Know Nashville.
            </p>
            <p>
              This Privacy Policy applies to our app, and its associated
              subdomains (collectively, our "Service") alongside our
              application, Now You Know Nashville. By accessing or using our
              Service, you signify that you have read, understood, and agree to
              our collection, storage, use, and disclosure of your personal
              information as described in this Privacy Policy and our Terms of
              Service.
            </p>
            <h2>Definitions and Key Terms</h2>
            <p>
              To help explain things as clearly as possible in this Privacy
              Policy, every time any of these terms are referenced, are strictly
              defined as:
            </p>
            <ul>
              <li>
                <strong>Cookie:</strong> small amount of data generated by a
                website and saved by your web browser. It is used to identify
                your browser, provide analytics, remember information about you
                such as your language preference or login information.
              </li>
              <li>
                <strong>Company:</strong> when this policy mentions "Company,"
                "we," "us," or "our," it refers to Now You Know Nashville, (PO
                Box 128441, Nashville, TN, 37212), that is responsible for your
                information under this Privacy Policy.
              </li>
              <li>
                <strong>Country:</strong> where Now You Know Nashville or the
                owners/founders of Now You Know Nashville are based, in this
                case is United States.
              </li>
              <li>
                <strong>Customer:</strong> refers to the company, organization,
                or person that signs up to use the Now You Know Nashville
                Service to manage the relationships with your consumers or
                service users.
              </li>
              <li>
                <strong>Device:</strong> any internet-connected device such as a
                phone, tablet, computer, or any other device that can be used to
                visit Now You Know Nashville and use the services.
              </li>
              <li>
                <strong>IP address:</strong> Every device connected to the
                Internet is assigned a number known as an Internet protocol (IP)
                address. These numbers are usually assigned in geographic
                blocks. An IP address can often be used to identify the location
                from which a device is connecting to the Internet.
              </li>
              <li>
                <strong>Personnel:</strong> refers to those individuals who are
                employed by Now You Know Nashville or are under contract to
                perform a service on behalf of one of the parties.
              </li>
              <li>
                <strong>Personal Data:</strong> any information that directly,
                indirectly, or in connection with other information - including
                a personal identification number - allows for the identification
                or identifiability of a natural person.
              </li>
              <li>
                <strong>Service:</strong> refers to the service provided by Now
                You Know Nashville as described in the relative terms (if
                available) and on this platform.
              </li>
              <li>
                <strong>Third-party service:</strong> refers to advertisers,
                contest sponsors, promotional and marketing partners, and others
                who provide our content or whose products or services we think
                may interest you.
              </li>
              <li>
                <strong>App/Application:</strong> Now You Know Nashville app,
                refers to the SOFTWARE PRODUCT identified above.
              </li>
              <li>
                <strong>You:</strong> a person or entity that is registered with
                Now You Know Nashville to use the Services.
              </li>
            </ul>
            <h2>What Information Do We Collect?</h2>
            <p>
              We collect information from you when you visit our app, register
              on our site, place an order, subscribe to our newsletter, respond
              to a survey, or fill out a form.
            </p>
            <ul>
              <li>Name / Username</li>
              <li>Email Addresses</li>
              <li>Debit/credit card numbers</li>
              <li>Password</li>
            </ul>
            <p>
              We also collect information from mobile devices for a better user
              experience, although these features are completely optional:
            </p>
            <ul>
              <li>
                Location (GPS): Location data helps to create an accurate
                representation of your interests, and this can be used to bring
                more targeted and relevant ads to potential customers.
              </li>
            </ul>
            <h2>How Do We Use The Information We Collect?</h2>
            <p>
              Any of the information we collect from you may be used in one of
              the following ways:
            </p>
            <ul>
              <li>
                To personalize your experience (your information helps us to
                better respond to your individual needs)
              </li>
              <li>
                To improve our app (we continually strive to improve our app
                offerings based on the information and feedback we receive from
                you)
              </li>
              <li>
                To improve customer service (your information helps us to more
                effectively respond to your customer service requests and
                support needs)
              </li>
              <li>To process transactions</li>
              <li>
                To administer a contest, promotion, survey or other app feature
              </li>
              <li>To send periodic emails</li>
            </ul>
            <h2>Do We Use Cookies?</h2>
            <p>
              Yes. Cookies are small files that a site or its service provider
              transfers to your computer's hard drive through your web browser
              (if you allow) that enables the site's or service provider's
              systems to recognize your browser and capture and remember certain
              information.
            </p>
            <h2>Do We Disclose Any Information To Outside Parties?</h2>
            <p>
              We do not sell, trade, or otherwise transfer to outside parties
              your personally identifiable information. This does not include
              trusted third parties who assist us in operating our app,
              conducting our business, or servicing you, so long as those
              parties agree to keep this information confidential. We may also
              release your information when we believe release is appropriate to
              comply with the law, enforce our app policies, or protect ours or
              others rights, property, or safety.
            </p>
            <h2>Third Party Links</h2>
            <p>
              Occasionally, at our discretion, we may include or offer third
              party products or services on our app. These third party sites
              have separate and independent privacy policies. We therefore have
              no responsibility or liability for the content and activities of
              these linked sites. Nonetheless, we seek to protect the integrity
              of our app and welcome any feedback about these sites.
            </p>
            <h2>California Online Privacy Protection Act Compliance</h2>
            <p>
              Because we value your privacy we have taken the necessary
              precautions to be in compliance with the California Online Privacy
              Protection Act. We therefore will not distribute your personal
              information to outside parties without your consent.
            </p>
            <h2>Children's Online Privacy Protection Act Compliance</h2>
            <p>
              We are in compliance with the requirements of COPPA (Children's
              Online Privacy Protection Act), we do not collect any information
              from anyone under 13 years of age. Our app, products and services
              are all directed to people who are at least 13 years old or older.
            </p>
            <h2>Your Consent</h2>
            <p>By using our app, you consent to our app privacy policy.</p>
            <h2>Changes To Our Privacy Policy</h2>
            <p>
              If we decide to change our privacy policy, we will update the
              Privacy Policy modification date below. This policy was last
              modified on January 1st, 2024.
            </p>
            <h2>Contacting Us</h2>
            <p>
              If there are any questions regarding this privacy policy you may
              contact us using the information below:
            </p>
            <ul>
              <li>Now You Know Nashville</li>
              <li>PO Box 128441, Nashville, TN, 37212</li>
              <li>United States</li>
              <li>info@nowyouknownashville.com</li>
            </ul>
          </div>
        </div>
      </div>
    </div>
  );
};

export default Privacy;
